CREATE EXTERNAL TABLE IF NOT EXISTS usaspending.assistance (
  `award_id_fain` string,
  `modification_number` string,
  `award_id_uri` string,
  `sai_number` string,
  `federal_action_obligation` double,
  `non_federal_funding_amount` double,
  `total_funding_amount` double,
  `face_value_of_loan` double,
  `original_subsidy_cost` double,
  `total_subsidy_cost` double,
  `total_loan_value` double,
  `action_date` date,
  `period_of_performance_start_date` date,
  `period_of_performance_current_end_date` date,
  `awarding_agency_code` string,
  `awarding_agency_name` string,
  `awarding_sub_agency_code` string,
  `awarding_sub_agency_name` string,
  `awarding_office_code` string,
  `awarding_office_name` string,
  `funding_agency_code` string,
  `funding_agency_name` string,
  `funding_sub_agency_code` string,
  `funding_sub_agency_name` string,
  `funding_office_code` string,
  `funding_office_name` string,
  `recipient_duns` string,
  `recipient_name` string,
  `recipient_parent_name` string,
  `recipient_parent_duns` string,
  `recipient_country_code` string,
  `recipient_country_name` string,
  `recipient_address_line_1` string,
  `recipient_address_line_2` string,
  `recipient_city_code` string,
  `recipient_city_name` string,
  `recipient_county_code` string,
  `recipient_county_name` string,
  `recipient_state_code` string,
  `recipient_state_name` string,
  `recipient_zip_code` string,
  `recipient_zip_last_4_code` string,
  `recipient_congressional_district` string,
  `recipient_foreign_city_name` string,
  `recipient_foreign_province_name` string,
  `recipient_foreign_postal_code` string,
  `primary_place_of_performance_country_code` string,
  `primary_place_of_performance_country_name` string,
  `primary_place_of_performance_code` string,
  `primary_place_of_performance_city_name` string,
  `primary_place_of_performance_county_code` string,
  `primary_place_of_performance_county_name` string,
  `primary_place_of_performance_state_name` string,
  `primary_place_of_performance_zip_4` string,
  `primary_place_of_performance_congressional_district` string,
  `primary_place_of_performance_foreign_location` string,
  `cfda_number` string,
  `cfda_title` string,
  `assistance_type_code` string,
  `assistance_type_description` string,
  `award_description` string,
  `business_funds_indicator_code` string,
  `business_funds_indicator_description` string,
  `business_types_code` string,
  `business_types_description` string,
  `correction_delete_indicator_code` string,
  `correction_delete_indicator_description` string,
  `action_type_code` string,
  `action_type_description` string,
  `record_type_code` string,
  `record_type_description` string,
  `last_modified_date` timestamp
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = ',',
  'field.delim' = ','
) LOCATION 's3://research-bytes/awards/assistance/'
TBLPROPERTIES ('has_encrypted_data'='false', 'skip.header.line.count'='1');
